### ISSUE TITLE
[Not an issue] PKGBUILD for Arch Linux

### ISSUE THREAD

**Issue by sirlucjan** [goldstar611/gitless#15]
I have prepared PKGBUILD for Arch Linux. Thanks for your work. If you want, you can put it in the README.

https://github.com/archlinux-lucjan/archlinux-packages/tree/master/gitless-git

**Comment by goldstar611** [comment]
Hi @sirlucjan, thanks for adding this to your AUR (I think that's the correct way to say it, I'm not an Arch user :P)

I'm more than happy to update the requirements to depend on a newer version of pygit2, I noticed your patch file changes the exact requirement to a greater than or equal requirement. Just let me know if you have or have not received any negative feedback from Arch users with a later pygit2 version.

Also, I don't believe there's a dependency on `python-sh` anymore since commit https://github.com/goldstar611/gitless/commit/b4755d742084ab553292a51a19f922665e645c5a

The `python-clint` dependency was also removed as of commit https://github.com/goldstar611/gitless/commit/516d96187cad6f1e4c5dea6861e625c15be41ca5

Hope that helps clear your build script up!

**Comment by sirlucjan** [comment]
gitless-git is already in AUR but uses old sources. I might talk to a maintainer.

**Comment by sirlucjan** [comment]
I've been testing this patch for a while now and it's unlikely to cause problems. Nevertheless, I will be happy to get more feedback. I use it mainly because I had a problem with pygit2 update before (after pygit2 update it wouldn't work properly).

**Comment by sirlucjan** [comment]
OK, I adopted "stable" version:

https://aur.archlinux.org/packages/gitless

**Comment by sirlucjan** [comment]
Thanks a lot!

**Comment by it-is-wednesday** [comment]
Hey, I've updated gitless-git to direct to this repo :)

**Comment by goldstar611** [comment]
> Hey, I've updated gitless-git to direct to this repo :)

I will update the readme to reflect your changes! Thanks for letting me know.
